# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SitePrediction
                                 A QGIS plugin
 This plugin aids researchers in modelling archaeological sites/areas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-20
        copyright            : (C) 2023 by Andrew Prentice
        email                : aaprentice@yahoo.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SitePrediction class from file SitePrediction.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .archaeo_modelling import SitePrediction
    return SitePrediction(iface)
